version: '3.7'
volumes:
  mysql_data:

services:
  mysql:
    container_name: "mysql_5.7.44"
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  web:
    container_name: "wordpress_php5.6"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    image: wordpress:php5.6
    volumes:
      - ./app_data:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 123456
    restart: always
